### ISSUE TITLE
Where can I get librevenge?

### ISSUE THREAD

**Issue by Andargor** [LibreOffice/libcdr#1]
Hi,

Trying to build on Ubuntu 12.04, I've got the prereqs including libwpd and libwpg (and the -dev packages). I get the following:

checking for REVENGE... no
configure: error: Package requirements (
        librevenge-0.0
) were not met:

No package 'librevenge-0.0' found

Where can I get this library?

**Comment by leonardorame** [comment]
sudo apt-get install librevenge-0.0-0
sudo apt-get install librevenge-dev

**Comment by dtardon** [comment]
This is a read-only mirror. Nobody watches it. Bug reports should go to https://bugs.documentfoundation.org .
